# Generated by Django 3.2.5 on 2021-11-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
        ('research', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='research',
            field=models.ManyToManyField(blank=True, help_text='Select associated research. In addition to items selected here, all research tagged for the selected projects will be listed.', related_name='task_research', to='research.Artifact'),
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_role', to='metrics.role'),
        ),
        migrations.AddField(
            model_name='task',
            name='score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_score_category', to='metrics.umuxscorecategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_browser', to='metrics.browser'),
        ),
        migrations.AddField(
            model_name='response',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_campaign', to='metrics.campaign'),
        ),
        migrations.AddField(
            model_name='response',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_city', to='metrics.city'),
        ),
        migrations.AddField(
            model_name='response',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_country', to='metrics.country'),
        ),
        migrations.AddField(
            model_name='response',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_device_type', to='metrics.devicetype'),
        ),
        migrations.AddField(
            model_name='response',
            name='goal_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_goal_completed', to='metrics.goalcompleted'),
        ),
        migrations.AddField(
            model_name='response',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_operating_system', to='metrics.operatingsystem'),
        ),
        migrations.AddField(
            model_name='response',
            name='primary_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_primary_goal', to='metrics.primarygoal'),
        ),
        migrations.AddField(
            model_name='response',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_state', to='metrics.state'),
        ),
        migrations.AddField(
            model_name='response',
            name='submitted_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='response_submitted_url', to='metrics.url'),
        ),
        migrations.AddField(
            model_name='response',
            name='user_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_user_role', to='metrics.userrole'),
        ),
        migrations.AddField(
            model_name='projectyearsetting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_year_setting_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectyearsetting',
            name='nps_baseline_score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_year_setting_nps_baseline_score_category', to='metrics.npsscorecategory'),
        ),
        migrations.AddField(
            model_name='projectyearsetting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_year_setting_project', to='metrics.project'),
        ),
        migrations.AddField(
            model_name='projectyearsetting',
            name='umux_baseline_score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_year_setting_umux_baseline_score_category', to='metrics.umuxscorecategory'),
        ),
        migrations.AddField(
            model_name='projectyearsetting',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_year_setting_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_snapshot_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshot_data_source', to='metrics.datasource'),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='goal_completed_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshot_goal_completed_category', to='metrics.goalcompletedcategory'),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='nps_score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshot_nps_score_category', to='metrics.npsscorecategory'),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_snapshot_project', to='metrics.project'),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='umux_score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_snapshot_umux_score_category', to='metrics.umuxscorecategory'),
        ),
        migrations.AddField(
            model_name='projectsnapshot',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_snapshot_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_event_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_event_project', to='metrics.project'),
        ),
        migrations.AddField(
            model_name='projectevent',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_event_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='project_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='current_year_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_current_year_settings', to='metrics.projectyearsetting'),
        ),
        migrations.AddField(
            model_name='project',
            name='currently_reporting_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_currently_reporting_snapshot', to='metrics.projectsnapshot'),
        ),
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_domain', to='metrics.domain'),
        ),
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='project_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='project_keywords', to='metrics.ProjectKeyword'),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_snapshot_by_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_latest_snapshot_by_date', to='metrics.projectsnapshot'),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_valid_currently_reporting_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_latest_valid_currently_reporting_snapshot', to='metrics.projectsnapshot'),
        ),
        migrations.AddField(
            model_name='project',
            name='latest_valid_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_latest_valid_snapshot', to='metrics.projectsnapshot'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherresponse',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_response_campaign', to='metrics.campaign'),
        ),
        migrations.AddField(
            model_name='npsscorecategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nps_score_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npsscorecategory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nps_score_category_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npslettergrade',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nps_letter_grade_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npslettergrade',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nps_letter_grade_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalcompletedcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_completed_category_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalcompletedcategory',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_completed_category_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_response_campaign', to='metrics.campaign'),
        ),
        migrations.AddField(
            model_name='domainyearsnapshot',
            name='core_projects_nps_letter_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_year_snapshot_core_projects_nps_letter_grade', to='metrics.npslettergrade'),
        ),
        migrations.AddField(
            model_name='domainyearsnapshot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_year_snapshot_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainyearsnapshot',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_year_snapshot_domain', to='metrics.domain'),
        ),
        migrations.AddField(
            model_name='domainyearsnapshot',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_year_snapshot_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='domain_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data_source_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_project', to='metrics.project'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_domain', to='metrics.domain'),
        ),
        migrations.AddField(
            model_name='alert',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_project', to='metrics.project'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_change_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VoteResponse',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metrics.response',),
        ),
    ]
