# Generated by Django 3.2.5 on 2022-01-24 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackResponseKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('responses_imported_count', models.PositiveIntegerField(blank=True, null=True)),
                ('projects_affected_count', models.PositiveIntegerField(blank=True, null=True)),
                ('run_time_seconds', models.FloatField()),
                ('import_type', models.CharField(choices=[('beeheard', 'BeeHeard'), ('usabilla', 'Usabilla')], max_length=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usabilla_import_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='feedback_response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='latest_feedback_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='latest_other_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='other_response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vote_response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='feedback_response_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='domainyearsnapshot',
            name='year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins have full edit access to the project info, can add other admins and editors, and can see emails in responses', related_name='project_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Contact is the owner and has full edit access to the project info, can add other admins and editors, and can see emails in responses', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contact', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Editors can only create/edit manual snapshots and can see emails in responses', related_name='project_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectyearsetting',
            name='year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.DeleteModel(
            name='UsabillaImportLog',
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='feedback_response_keywords', to='metrics.FeedbackResponseKeyword'),
        ),
    ]
